################################################################################################################################################################

# @project        Library ▸ I/O
# @file           .codecov.yml
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        Apache License 2.0

################################################################################################################################################################

fixes:

    - "testbuild/::"

################################################################################################################################################################
